name: Trigger auto deployment for container-app-q4us7ck3q4l5w

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-q4us7ck3q4l5w-AutoDeployTrigger-28444d79-f1cd-4fa6-a22c-5194c549bcc2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQ4US7CK3Q4L5W_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQ4US7CK3Q4L5W_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQ4US7CK3Q4L5W_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPQ4US7CK3Q4L5W_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPQ4US7CK3Q4L5W_REGISTRY_PASSWORD }}
          containerAppName: container-app-q4us7ck3q4l5w
          resourceGroup: appspacesfastapia9b082f2
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


